name: Deploy Vite Page with Yarn

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
           node-version: '13.13.0'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Dependencies
        run: yarn install
      - name: Build Site
        run: yarn build
      - name: Package Site as Artifact
        run: tar -czvf dist.tar.gz ./dist
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
           name: site_build # optional, default is artifact
           path: dist.tar.gz

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
           node-version: '16.16.0'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Dependencies
        run: yarn install
      - name: Build Site
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          ssh-key: ${{ secrets.DEPLOY_KEY }}